const express=require("express");
const router=express.Router();
const {createSubject,getSubjectByBoard,getSubjectById,deleteSubject}=require("../controllers/subject.controller");
const requireUser = require("../middleware/requireUser");
const requireAdminPermission = require("../middleware/requireAdminPermission");
router.post("/", requireUser(["admin", "staff"]), requireAdminPermission("content"), createSubject);
router.get("/board/:boardId",getSubjectByBoard);
router.get("/:id",getSubjectById);
router.delete("/:id", requireUser(["admin", "staff"]), requireAdminPermission("content"), deleteSubject);
module.exports=router;
